### ISSUE TITLE
build braking mac os 

### ISSUE THREAD

**Issue by AmosG** [codingwithjustin/vue3-electron#2]
INFO  Bundling render process:

⠋  Building modern bundle for production.../Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^

TypeError: Invalid Version: 11
    at new SemVer (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/node_modules/semver/classes/semver.js:38:13)
    at compare (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/node_modules/semver/functions/gte.js:2:30)
    at chainWebpack (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:9:30)
    at /Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/index.js:55:5
    at /Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at PluginAPI.resolveChainableWebpackConfig (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/commands/build/index.js:74:15
    at Service.run (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at /Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/vue-cli-plugin-electron-builder/index.js:152:29
    at Service.run (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/amos.gutman/dev/electron-mk1/workin-electron/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by gvansick** [comment]
I have the same issue. Note - electron:build works perfectly. It's electron:serve that results in this error.
